/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pang_sopang_testso_JniUtils */

#ifndef _Included_com_pang_sopang_testso_JniUtils
#define _Included_com_pang_sopang_testso_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pang_sopang_testso_JniUtils
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pang_sopang_testso_JniUtils_getHwPubKey
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_pang_sopang_testso_JniUtils_getHwPrivateKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
